---
- name: install python3-apt
  ansible.builtin.package:
    name: python3-apt
    state: present

- name: Update && upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    state: latest

- name: Install software
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ software }}"
    state: latest
