---
- name: install python3-apt
  package:
    name: python3-apt
    state: present

- name: Update && upgrade
  apt:
    update_cache: yes
    upgrade: yes
    state: latest

- name: Install software
  apt:
    update_cache: yes
    name: "{{ software }}"
    state: latest
