---

version: '2.29.7'

services:
  ubuntu_ssh:
    build: .
    container_name: ubuntu_ansible
    secrets:
      - host_ssh_key
    ports:
      - "2233:23"
    networks:
      - ssh_net
    restart: unless-stopped

secrets:
  host_ssh_key:
    file: .secrets/authorized_keys

networks:
  ssh_net:
    driver: bridge
