---

services:
  ubuntu_ssh:
    build: .
    container_name: ubuntu_ansible
    environment:
      - SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
    ports:
      - "2233:23"
    networks:
      - ssh_net
    restart: unless-stopped

networks:
  ssh_net:
    driver: bridge
