---
- name: Configure users and groups on Docker container
  hosts: all
  roles:
    - roles/users_role

- name: Install ZSH
  hosts: all
  roles:
    - roles/install_zsh

- name: Apply SSH configuration
  hosts: all
  roles:
    - ssh_config

- name: install software
  hosts: all
  roles: 
    - software

- name: install and launch nginx webserver
  hosts: all
  roles:
    - nginx
