---

- name: Ensure Zsh is installed
  ansible.builtin.package:
    name: zsh
    state: present

- name: Install Oh My Zsh for users with Zsh shell
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ item.name }}/.oh-my-zsh"
  loop: "{{ users }}"
  when: item.shell == "/bin/zsh"
  become: true
  become_user: "{{ item.name }}"

- name: Set Zsh as default shell for Zsh users
  ansible.builtin.shell: "chsh -s /bin/zsh {{ item.name }}"
  loop: "{{ users }}"
  when: item.shell == "/bin/zsh"

